Add py client
asokol123/yggdrasil-dns pull request #1
Opened 2022-03-20 12:04 UTC by FelipeMassa2018

2022-03-20 12:24 UTC, MCPN requested changes
и нет proof of work (поле nonce)

2022-03-20 12:24 UTC, MCPN commented on py/main.py
> +    print(f"Request: {request.json()}.")
Response

2022-03-20 12:24 UTC, MCPN commented on py/main.py
> +    request_params["key"] = hash_key
signature

2022-03-20 12:24 UTC, MCPN commented on py/main.py
> +    key = os.environ.get(args.key_name)
Не уверен, что стоит передавать имя ключа, лучше просто делать os.environ['SECRET_KEY'] (заодно проверка на то что ключ есть)

2022-03-20 12:24 UTC, MCPN commented on py/main.py
> +    current_timestamp = time.time()
Лучше int(time.time())

2022-03-20 12:24 UTC, MCPN commented on py/main.py
> +    if args.address is not None:
Лучше сделай через подпарсеры

2022-03-20 12:24 UTC, MCPN commented on py/main.py
> +    parser.add_argument('--machine', '-m', help='machine to send request to', type=int, required=True)
endpoint

2022-03-20 12:24 UTC, MCPN commented on py/main.py
> +    request = requests.post(args.machine, json=request_params, timeout=args.timeout)
думаю, что в endpoint будет передаваться только адрес, а путь стоит добавить в зависимости от команды

2022-03-20 12:37 UTC, FelipeMassa2018 commented on py/main.py
> +    if args.address is not None:
Что есть подпарсеры?

2022-03-20 13:08 UTC, MCPN commented on py/main.py
> +    if args.address is not None:
https://docs.python.org/3/library/argparse.html#sub-commands

2022-03-20 13:13 UTC, asokol123 commented on py/main.py
> +    hash_key = hmac.new(key, request_params, hashlib.sha256).hexdigest()
Это выглядит не очень удобно для бекенда, потому что request params не однозначно в строку превращается, но хз как делать удобно.

2022-03-20 13:15 UTC, MCPN commented on py/main.py
> +    hash_key = hmac.new(key, request_params, hashlib.sha256).hexdigest()
По идее это не так кстати, потому что словари в питоне теперь детерминированные, но тоже слегка пугает. Найду потом, как у нас в проекте словарь подписывается

2022-03-20 13:58 UTC, asokol123 commented on py/main.py
> +    hash_key = hmac.new(key, request_params, hashlib.sha256).hexdigest()
Можно попробовать использовать [JWT](https://pyjwt.readthedocs.io/en/stable/) в теории

2022-03-20 15:17 UTC, FelipeMassa2018 commented on py/main.py
> +    hash_key = hmac.new(key, request_params, hashlib.sha256).hexdigest()
можно json.dumps, будет строка

2022-03-20 15:25 UTC, MCPN commented on py/main.py
> +    hash_key = hmac.new(key, request_params, hashlib.sha256).hexdigest()
Да не, проблема же в том, что в словаре порядок неопределенный (на самом определенный, но в порядке вставки, из-за чего registry все равно проблематично проверить правильность подписи)
Тривиальное решение: `msg=urlencode(sorted(params.items(), key=itemgetter(0))).encode('utf-8')` (вместо  `urlencode` можно `json.dumps`), на registry тоже отсортировать ключи перед проверкой.

2022-03-20 17:24 UTC, FelipeMassa2018 commented on py/main.py
> +    hash_key = hmac.new(key, request_params, hashlib.sha256).hexdigest()
а, боже, понял

2022-03-20 17:25 UTC, FelipeMassa2018 commented on py/main.py
> +    print(f"Request: {request.json()}.")
Не совсем понял, результат requests.post и есть response(он же ответ)?

2022-03-20 17:26 UTC, MCPN commented on py/main.py
> +    print(f"Request: {request.json()}.")
не, я имел в виду `f"Response: {request.json()}."`

2022-03-22 19:20 UTC, MCPN commented on py/main.py
> +        hash_key = hmac.new(key, json.dumps(dict(sorted(request_params.items()))).encode('utf-8'), hashlib.sha256).hexdigest()
не, здесь просто sha256, без hmac

2022-03-22 19:20 UTC, MCPN commented on py/main.py
> +        if hash_key[0:args.n] == "0" * args.n:
hash_key.startswith(...)

2022-03-22 19:20 UTC, MCPN commented on py/main.py
> +    parser.add_argument('--key-name', '-k', help='name of the key for hash', dest='key_name', type=str, required=True)
не используется

2022-03-22 19:20 UTC, MCPN commented on py/main.py
> +    parser.add_argument('--timeout', '-t', help='request timeout', type=int, required=True)
не уверен, что прям нужный параметр; по крайней мере добавь дефолт, например в 5 сек

2022-03-22 19:43 UTC, FelipeMassa2018 commented on py/main.py
> +        if hash_key[0:args.n] == "0" * args.n:
... окей, ща будет

2022-03-22 19:44 UTC, FelipeMassa2018 commented on py/main.py
> +        hash_key = hmac.new(key, json.dumps(dict(sorted(request_params.items()))).encode('utf-8'), hashlib.sha256).hexdigest()
ты уверен, в том, что это тут не надо? Прост в том коде, что я нагуглил, там было ровно так написано. И ручками я тестил этот кусок кода, все работает ровно как надо.

2022-03-22 19:46 UTC, FelipeMassa2018 commented on py/main.py
> +        hash_key = hmac.new(key, json.dumps(dict(sorted(request_params.items()))).encode('utf-8'), hashlib.sha256).hexdigest()
я не разбирался, какая функция что конкретно делает, но без hmac получается полный мусор

2022-03-22 19:54 UTC, asokol123 commented on py/main.py
> +        hash_key = hmac.new(key, json.dumps(dict(sorted(request_params.items()))).encode('utf-8'), hashlib.sha256).hexdigest()
Тут точно нужно просто `hashlib.sha256`. Мы не шифруем ничего секретного, и ключ не нужен, задача - просто набрутить `nonce`, а `hmac` просто про шифрование. И вроде нет, не полный мусор получается

2022-03-22 20:04 UTC, MCPN commented on py/main.py
> +        hash_key = hmac.new(key, json.dumps(dict(sorted(request_params.items()))).encode('utf-8'), hashlib.sha256).hexdigest()
`hashlib.sha256(json.dumps(d).encode()).hexdigest()` нормально отрабатывает
бтв, тут сортировать словарь не нужно - проверяться в registry будет именно то, что ты отправишь

2022-03-22 20:06 UTC, FelipeMassa2018 commented on py/main.py
> +        hash_key = hmac.new(key, json.dumps(dict(sorted(request_params.items()))).encode('utf-8'), hashlib.sha256).hexdigest()
Стоп, а зачем нам pow, если мы ничего не шифруем? Я думал суть в том, что мы добавляем какой-то зашифрованный ключ, который проверяется с другой стороны на соответствие(оба знаем алгоритм шифрования и проверяем, что все окей) или около того

P.S. а, всм сортировать словарь надо при создании запроса?

2022-03-22 20:08 UTC, MCPN commented on py/main.py
> +        hash_key = hmac.new(key, json.dumps(dict(sorted(request_params.items()))).encode('utf-8'), hashlib.sha256).hexdigest()
pow вообще не про шифрование, про это подпись)
pow это про защиту от спама в данном случае, что ты потратил некоторое процессорное время перед тем как отправить запрос
а сортировать словарь вообще не нужно

2022-03-22 20:34 UTC, FelipeMassa2018 commented on py/main.py
> +        hash_key = hmac.new(key, json.dumps(dict(sorted(request_params.items()))).encode('utf-8'), hashlib.sha256).hexdigest()
ок

2022-03-24 14:29 UTC, merged